### ISSUE TITLE
Breaking changes list for noni 2.0 [meta]

### ISSUE THREAD

**Issue by metasansana** [quenktechnologies/noni#74]
This list tracks all the breaking changes expected for noni 2.0. Some may be implemented in minor releases if they are safe enough but the idea is to tackle them in one branch then merge so dependents can update in one go.

- [ ] Remove usage of Type from DoFn.
- [ ] Remove unused monad and related category theory based functions and modules.
- [ ] Move free and future one level up to control.
- [ ] Bring preconditions into noni.
- [ ] Provide generic functions for common operations on records/lists.
